# @name accountPost
post http://localhost:3000/api/v1/account
Content-Type: application/json

{
    "email": "mail@gmail.com",
    "username": "username",
    "password": "password"
}

###

# @name accountRolePost
@account_id = {{accountPost.response.body.$.result.$.id}}

post http://localhost:3000/api/v1/account/{{account_id}}/role
Content-Type: application/json

{
    "role": "provider"
}

###

# @name accountRoleGet
@account_role = "PROVIDER"

get http://localhost:3000/api/v1/account/{{account_id}}/role/{{account_role}}
