/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.account.controller;

import com.account.model.ErrorResponse;
import com.account.model.RequestModel;
import com.account.model.ReturnModel;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
public interface AccountApi {

    /**
     * POST /api/v1/account
     * Creates new account and stores it into database
     *
     * @param requestModel account to be added (required)
     * @return Created (status code 201)
     *         or Bad request. Email must be present and valid, username must be over 5 characters long, password must be present and over 8 characters long (only numbers and characters) (status code 400)
     *         or Conflict, email/username already exists (status code 409)
     *         or unexpected error (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/account",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<ReturnModel> apiV1AccountPost(
         @RequestBody RequestModel requestModel
    ) throws Exception;

}
